COLORMAP = {
  "dark denim":"black", 
  "dark navy":"blue",
  "ash":"grey",
  "bordeaux":"red",
  "mahagoni":"red",
  "gold":"yellow",
  "dark oliv":"green",
  "striped":"other",
  "anthracite":"black", 
  "antique pink":"red",
  "floral":"other", 
  "baltic blue":"blue",
  "nature":"other", 
  "ancient":"other", 
  "curry":"yellow",
  "turquoise":"blue",
  "navy":"blue",
  "brown":"brown",
  "aubergine":"red",
  "mocca":"brown", 
  "blau":"blue",
  "basalt":"grey",
  "azure":"blue",
  "coral":"red", 
  "pallid":"grey", 
  "petrol":"blue",
  "silver":"grey",
  "habana":"red", 
  "darkblue":"blue",
  "beige":"yellow", 
  "mint":"green",
  "khaki":"brown",
  "hibiscus":"red",
  "orange":"red", 
  "yellow":"yellow",
  "black":"black",
  "blue":"blue",
  "purple":"red",
  "almond":"brown",
  "red":"red",
  "berry":"red",
  "grey":"grey",
  "ocher":"brown",
  "avocado":"green",
  "magenta":"red",
  "olive":"green",
  "white":"white",
  "denim":"other", 
  "pink":"red",
  "stained":"brown",
  "kanel":"brown", 
  "green":"green",
  "jade":"green",
  "aquamarine":"blue",
  "aqua":"blue",
  "ecru":"grey",
  "iron":"grey",
  "fuchsia":"red",
  "ingwer":"red",
  "cognac":"brown",
  "terracotta":"brown",
  "apricot":"yellow",
  "graphite":"grey",
  "crimson":"red",
  "lemon":"yellow",
  "oliv":"green",
  "leopard":"yellow",
  "amethyst":"red",
  "aviator":"other", 
  "bronze":"brown",
  "brwon":"brown",
  "caramel":"yellow",
  "champagner":"yellow", 
  "cobalt blue":"blue",
  "copper coin":"brown",
  "cortina mocca":"brown",
  "creme":"yellow",
  "curled":"other",
  "currant purple":"red",
  "dark garnet":"black",
  "dark grey":"grey",
  "ebony":"black",
  "ivory":"white",
  "mango":"yellow",
  "opal":"other",
  "perlmutt":"other", 
  "vanille":"white"
  }