

COLORMAP = {
  "denim":"blue",
  "dark denim":"black", 
  "dark navy":"darkblue",
  "ash":"grey",
  "bordeaux":"red",
  "mahagoni":"red",
  "gold":"gold",
  "dark oliv":"olive",
  "anthracite":"black", 
  "antique pink":"pink", 
  "baltic blue":"aqua",
  "curry":"yellow",
  "turquoise":"turquoise",
  "navy":"navy",
  "brown":"brown",
  "aubergine":"red",
  "mocca":"brown", 
  "blau":"blue",
  "basalt":"grey",
  "azure":"blue",
  "coral":"coral", 
  "pallid":"grey", 
  "petrol":"blue",
  "silver":"silver",
  "habana":"red", 
  "darkblue":"darkblue",
  "beige":"yellow", 
  "mint":"lightgreen",
  "khaki":"khaki",
  "hibiscus":"red",
  "orange":"orange", 
  "yellow":"yellow",
  "black":"black",
  "blue":"blue",
  "purple":"purple",
  "almond":"brown",
  "red":"red",
  "berry":"red",
  "grey":"grey",
  "ocher":"brown",
  "avocado":"green",
  "magenta":"magenta",
  "olive":"olive",
  "white":"white",
  "pink":"pink",
  "stained":"brown",
  "kanel":"brown", 
  "green":"green",
  "jade":"green",
  "aquamarine":"aquamarine",
  "aqua":"aqua",
  "ecru":"grey",
  "iron":"grey",
  "fuchsia":"fuchsia",
  "ingwer":"red",
  "cognac":"brown",
  "terracotta":"brown",
  "apricot":"yellow",
  "graphite":"grey",
  "crimson":"red",
  "lemon":"yellow",
  "oliv":"olive",
  "leopard":"yellow",
  "amethyst":"red",
  "bronze":"brown",
  "brwon":"brown",
  "caramel":"yellow",
  "champagner":"yellow", 
  "cobalt blue":"blue",
  "copper coin":"brown",
  "cortina mocca":"brown",
  "creme":"yellow",
  "currant purple":"red",
  "dark garnet":"black",
  "dark grey":"grey",
  "ebony":"black",
  "ivory":"ivory",
  "mango":"yellow",
  "vanille":"white",
  }